[tool.poetry]
name = "blog-app"
version = "0.1.0"
description = ""
authors = ["Suren Khorenyan <surenkhorenyan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.68.0"
uvicorn = "^0.15.0"
SQLAlchemy = "^1.4.22"
asyncpg = "^0.24.0"
aiohttp = "^3.7.4"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
alembic = "^1.6.5"
psycopg2 = "^2.9.1"
locust = "^2.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
